[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "ng run build:ssr --configuration production"
  publish = "dist/angular-firebase-todo/browser"

[functions]
  included_files = ["dist/**"]