[[redirects]]
  from = "/*"
  to = ".netlify/functions/start"
  status = 200

[build]
  command = "npm run build:ssr"
  publish = "dist/angular-firebase-todo/browser"

[functions]
  included_files = ["dist/**"]