[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "ng build --configuration production && ng run angular-firebase-todo:serverless:production"
  publish = "dist/angular-firebase-todo/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"